// DADOS DEMONSTRATIVOS: substitua textos, imagens e contatos pelos dados reais autorizados.
// LINKAR ANÚNCIO OFICIAL DA ONG: em cada animal source="ONG", adicione "adoptionUrl": "https://..." com a página oficial daquele pet. O site usa ong.site como alternativa.
window.PETLAR_ANIMAIS = [{
        "id": "mel",
        "name": "Mel",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "luna-pessoa",
        "name": "Luna",
        "species": "Gato",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "thor",
        "name": "Thor",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "max-pessoa",
        "name": "Max",
        "species": "Cachorro",
        "age": "6 meses",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://images.unsplash.com/photo-1551717743-49959800b1f6?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "nina",
        "name": "Nina",
        "species": "Gato",
        "age": "2 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "pessoa-1",
        "name": "Luna",
        "species": "Gato",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-2",
        "name": "Max",
        "species": "Cachorro",
        "age": "6 meses",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://images.unsplash.com/photo-1551717743-49959800b1f6?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-3",
        "name": "Bento",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Mariana",
        "image": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-4",
        "name": "Amora",
        "species": "Gato",
        "age": "3 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "Pessoa",
        "guardian": "João",
        "image": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-5",
        "name": "Pipoca",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Beatriz",
        "image": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-6",
        "name": "Nino",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-7",
        "name": "Cacau",
        "species": "Cachorro",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-8",
        "name": "Tico",
        "species": "Gato",
        "age": "8 meses",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Mariana",
        "image": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-9",
        "name": "Belinha",
        "species": "Cachorro",
        "age": "7 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "Pessoa",
        "guardian": "João",
        "image": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-10",
        "name": "Simba",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "Pessoa",
        "guardian": "Beatriz",
        "image": "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-11",
        "name": "Mel",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-12",
        "name": "Pérola",
        "species": "Gato",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-13",
        "name": "Fred",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Mariana",
        "image": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "patinhas-2",
        "name": "Alan",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "CÃO SEM DONO",
        "image": "./assets/imagens/animais/alann.png",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Caramelo",
        "coat": "Curto",
        "neutered": "Sim",
        "vaccinated": "Sim",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "amor-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "vida-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "resgate-1",
        "name": "Sol",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "novo-lar-1",
        "name": "Sol",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    }

    , {
        "id": "coelho-nuvem",
        "name": "Nuvem",
        "species": "Coelho",
        "age": "8 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Manu Silva",
        "image": "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=900&q=85",
        "description": "Coelhinha tranquila que procura uma família cuidadosa e preparada para suas necessidades.",
        "color": "Branco",
        "coat": "Médio",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Precisa de espaço seguro e alimentação adequada",
        "ongId": "patinhas"
    },
    {
        "id": "ave-pipiu",
        "name": "Pipiu",
        "species": "Ave",
        "age": "1 ano",
        "sex": "Não informado",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Marina",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Ave dócil à procura de um lar responsável. Confirme a espécie e os cuidados necessários com o responsável.",
        "color": "Colorido",
        "coat": "Penas",
        "neutered": "Não se aplica",
        "vaccinated": "Não informado",
        "dewormed": "Não se aplica",
        "special": "Confirmar espécie e necessidades específicas",
        "ongId": null
    }

    , {
        "id": "coelho-nuvem",
        "name": "Nuvem",
        "species": "Coelho",
        "age": "8 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=900&q=85",
        "description": "Coelhinha tranquila que procura uma família cuidadosa e preparada para suas necessidades.",
        "color": "Branco",
        "coat": "Médio",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Precisa de espaço seguro e alimentação adequada",
        "ongId": "patinhas"
    },
    {
        "id": "ave-pipiu",
        "name": "Pipiu",
        "species": "Ave",
        "age": "1 ano",
        "sex": "Não informado",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Marina",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=900&q=85",
        "description": "Ave dócil à procura de um lar responsável. Confirme a espécie e os cuidados necessários com o responsável.",
        "color": "Colorido",
        "coat": "Penas",
        "neutered": "Não se aplica",
        "vaccinated": "Não informado",
        "dewormed": "Não se aplica",
        "special": "Confirmar espécie e necessidades específicas",
        "ongId": null
    }
];
window.PETLAR_ONGS = [{
        "id": "patinhas",
        "name": "CÃO SEM DONO",
        "city": "São Paulo, SP",
        "count": 15,
        "image": "./assets/imagens/animais/Cao sem dono.jpg",
        "description": "Acolhimento, cuidado e novas oportunidades para animais que precisam de uma família.",
        "site": "https://www.caosemdono.com.br/",
        "email": "caosemdono@com.br",
        "phone": "11 97863-4054",
        "history": "A CÃO SEM DONO trabalha para aproximar animais resgatados de famílias responsáveis.",
        "mission": "Promover bem-estar animal e adoções conscientes."
    },
    {
        "id": "amor",
        "name": "Amor Animal",
        "city": "Rio de Janeiro, RJ",
        "count": 15,
        "image": "./assets/imagens/animais/catland.png",
        "description": "Uma rede de pessoas dedicada ao resgate e à adoção responsável.",
        "site": "https://catland.org.br/",
        "email": "catland@org.br",
        "phone": "",
        "history": "O Amor Animal reúne voluntários que apoiam o cuidado e a adoção.",
        "mission": "Construir relações duradouras entre animais e famílias."
    },
    {
        "id": "vida",
        "name": "Vida de 4 Patas",
        "city": "Belo Horizonte, MG",
        "count": 15,
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=600&q=80",
        "description": "Cuidado, respeito e carinho em cada etapa da adoção.",
        "site": "",
        "email": "contato@exemplo.org",
        "phone": "",
        "history": "A Vida de 4 Patas promove a divulgação de animais que buscam um lar.",
        "mission": "Incentivar a adoção responsável e o respeito aos animais."
    },
    {
        "id": "resgate",
        "name": "Resgate Animal",
        "city": "Curitiba, PR",
        "count": 15,
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=600&q=80",
        "description": "Apoio a animais resgatados e conexão com novos lares.",
        "site": "",
        "email": "contato@exemplo.org",
        "phone": "",
        "history": "O Resgate Animal é um projeto demonstrativo de proteção animal.",
        "mission": "Ampliar oportunidades de adoção com informação e cuidado."
    },
    {
        "id": "novo-lar",
        "name": "Novo Lar",
        "city": "Santos, SP",
        "count": 15,
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=600&q=80",
        "description": "Pequenos gestos, grandes mudanças na vida dos animais.",
        "site": "",
        "email": "contato@exemplo.org",
        "phone": "",
        "history": "O Novo Lar divulga animais e orienta famílias interessadas.",
        "mission": "Ajudar cada animal a encontrar uma família preparada."
    }
];