// DADOS DEMONSTRATIVOS: substitua textos, imagens e contatos pelos dados reais autorizados.
// LINKAR ANÚNCIO OFICIAL DA ONG: em cada animal source="ONG", adicione "adoptionUrl": "https://..." com a página oficial daquele pet. O site usa ong.site como alternativa.
window.PETLAR_ANIMAIS = [{
        "id": "mel",
        "name": "Mel",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://plus.unsplash.com/premium_photo-1666777247416-ee7a95235559?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "luna-pessoa",
        "name": "Luna",
        "species": "Gato",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://plus.unsplash.com/premium_photo-1667030474693-6d0632f97029?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "thor",
        "name": "Thor",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1546447147-3fc2b8181a74?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "max-pessoa",
        "name": "Max",
        "species": "Cachorro",
        "age": "6 meses",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://plus.unsplash.com/premium_photo-1708983591032-40822c6afa84?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D   ",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "nina",
        "name": "Nina",
        "species": "Gato",
        "age": "2 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://plus.unsplash.com/premium_photo-1673967831980-1d377baaded2?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "pessoa-1",
        "name": "Luna",
        "species": "Gato",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://images.unsplash.com/photo-1787404200329-78b2aaee13c1?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-2",
        "name": "Max",
        "species": "Cachorro",
        "age": "6 meses",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-3",
        "name": "Bento",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Mariana",
        "image": "https://images.unsplash.com/photo-1560525821-d5615ef80c69?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-4",
        "name": "Amora",
        "species": "Gato",
        "age": "3 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "Pessoa",
        "guardian": "João",
        "image": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-5",
        "name": "Pipoca",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Beatriz",
        "image": "https://images.unsplash.com/photo-1575785662490-1e3ce6806ed5?q=80&w=756&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-6",
        "name": "Nino",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?q=80&w=736&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-7",
        "name": "Cacau",
        "species": "Cachorro",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://images.unsplash.com/photo-1523626797181-8c5ae80d40c2?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-8",
        "name": "Tico",
        "species": "Gato",
        "age": "8 meses",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Mariana",
        "image": "https://images.unsplash.com/photo-1561948955-570b270e7c36?q=80&w=601&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-9",
        "name": "Belinha",
        "species": "Cachorro",
        "age": "7 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "Pessoa",
        "guardian": "João",
        "image": "https://images.unsplash.com/photo-1455103493930-a116f655b6c5?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-10",
        "name": "Simba",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "Pessoa",
        "guardian": "Beatriz",
        "image": "https://images.unsplash.com/photo-1503777119540-ce54b422baff?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-11",
        "name": "Mel",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Ana",
        "image": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-12",
        "name": "Pérola",
        "species": "Gato",
        "age": "1 ano",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "Pessoa",
        "guardian": "Carlos",
        "image": "https://images.unsplash.com/photo-1543852786-1cf6624b9987?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "pessoa-13",
        "name": "Fred",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Mariana",
        "image": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=900&q=85",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": null
    },
    {
        "id": "patinhas-2",
        "name": "Alan",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "CÃO SEM DONO",
        "image": "./assets/imagens/animais/alann.png",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Caramelo",
        "coat": "Curto",
        "neutered": "Sim",
        "vaccinated": "Sim",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://plus.unsplash.com/premium_photo-1676389281733-aaefab0e7907?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1516371535707-512a1e83bb9a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1547525623-c7d42c20284c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1523480717984-24cba35ae1ef?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1472491235688-bdc81a63246e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1600352774373-7b992e5189de?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1568393691080-d016376b767d?q=80&w=1631&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1511044568932-338cba0ad803?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1735989967755-706e5edcb44b?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://plus.unsplash.com/premium_photo-1693932897536-c294c8a8ba0a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "patinhas-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://images.unsplash.com/photo-1571566882372-1598d88abd90?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "patinhas"
    },
    {
        "id": "amor-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1596490634801-c536934af56e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1640384974326-3e72680e0fb3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://plus.unsplash.com/premium_photo-1664303466454-b8ddd4943be4?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://plus.unsplash.com/premium_photo-1677181729027-a7873c1f6cb5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1455970022149-a8f26b6902dd?q=80&w=704&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://plus.unsplash.com/premium_photo-1667563115086-edf9a16d497a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://plus.unsplash.com/premium_photo-1661386016538-a393b5681e0b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://premierpet.com.br/wp-content/uploads/2024/08/model-banner-sphynx-mobile-v1-1024x1024.png",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1648047116702-498bb37a5f64?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1477973770766-6228305816df?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1626602411112-10742f9a3ab8?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1560781854-d3d74a1ba2ae?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1556796879-160fd67614ae?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "amor-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Rio de Janeiro, RJ",
        "source": "ONG",
        "guardian": "Amor Animal",
        "image": "https://images.unsplash.com/photo-1518288774672-b94e808873ff?q=80&w=738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "amor"
    },
    {
        "id": "vida-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://plus.unsplash.com/premium_photo-1695754439115-60e3807dbb26?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1536589961747-e239b2abbec2?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1599765625239-fe53131a58ee?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1605638868237-0660a05a135b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://objectstorage.sa-vinhedo-1.oraclecloud.com/n/axuh3s32sabm/b/cobasi-institutional-cms-bucket/o/prod/persa_branco.webp",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1612940960267-4549a58fb257?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://plus.unsplash.com/premium_photo-1668062459573-ab0ddf106283?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://premierpet.com.br/wp-content/uploads/2023/12/model-banner-siames-mobile-v1-1024x1024.png",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1562317305-58a17fe2c09e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1629102902031-7490bf7a6d41?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1492370284958-c20b15c692d2?q=80&w=749&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1493916665398-143bdeabe500?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1562054438-f127502ea154?q=80&w=1631&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "vida-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Belo Horizonte, MG",
        "source": "ONG",
        "guardian": "Vida de 4 Patas",
        "image": "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "vida"
    },
    {
        "id": "resgate-1",
        "name": "Sol",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1536809188428-e8ecf663d0be?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1475954704693-ac6850a71ee0?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1568152950566-c1bf43f4ab28?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1518378188025-22bd89516ee2?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1678203778548-5fa399d8e7fb?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1498100152307-ce63fd6c5424?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1610968755695-d7fcb5fd4b92?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1565194481104-39d1ee1b8bcc?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1606011334315-025e4baab810?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1565708097881-bbf4ecf47cc1?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1554956615-1ba6dc39921b?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1591608971358-f93643d11763?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1673474025690-eacc81e21daa?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "resgate-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Curitiba, PR",
        "source": "ONG",
        "guardian": "Resgate Animal",
        "image": "https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "resgate"
    },
    {
        "id": "novo-lar-1",
        "name": "Sol",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1555325084-b068599743c9?q=80&w=675&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-2",
        "name": "Pingo",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?q=80&w=767&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-3",
        "name": "Cookie",
        "species": "Gato",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-4",
        "name": "Floquinho",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1550450888-a1ad510ccacc?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-5",
        "name": "Jade",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1736196674354-b5e918a64644?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-6",
        "name": "Bidu",
        "species": "Gato",
        "age": "2 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1516280030429-27679b3dc9cf?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-7",
        "name": "Mimi",
        "species": "Cachorro",
        "age": "3 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1613210581288-ae09b0bdf17f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-8",
        "name": "Paçoca",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1593191798143-7f98dc35a98a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-9",
        "name": "Lili",
        "species": "Gato",
        "age": "5 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://labovet.com.br/wp-content/uploads/2024/11/GATOS-EXOTICOS-E-DIFERENCIADOS-DO-PLANETA.jpg",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-10",
        "name": "Zeca",
        "species": "Cachorro",
        "age": "1 anos",
        "sex": "Macho",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1621101164063-ba88826cb918?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-11",
        "name": "Nala",
        "species": "Cachorro",
        "age": "2 anos",
        "sex": "Fêmea",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://plus.unsplash.com/premium_photo-1754488045497-72f67ab84132?q=80&w=738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-12",
        "name": "Pudim",
        "species": "Gato",
        "age": "3 anos",
        "sex": "Macho",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://img.magnific.com/fotos-gratis/feche-o-gato-fofo-dentro-de-casa_23-2148882585.jpg?semt=ais_hybrid&w=740&q=80",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-13",
        "name": "Dora",
        "species": "Cachorro",
        "age": "4 anos",
        "sex": "Fêmea",
        "size": "Médio",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1509049369691-8a367c1cb174?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-14",
        "name": "Tobias",
        "species": "Cachorro",
        "age": "5 anos",
        "sex": "Macho",
        "size": "Grande",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://images.unsplash.com/photo-1545328951-d483a3667ed0?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    },
    {
        "id": "novo-lar-15",
        "name": "Kika",
        "species": "Gato",
        "age": "1 anos",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "Santos, SP",
        "source": "ONG",
        "guardian": "Novo Lar",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp6Dlhz27kenqFUCuoc4tkwCv4ZUIvhPm5ZCbEcrmvcPZ6GYYkxNeMVHjc&s=10",
        "description": "Perfil demonstrativo: entre em contato com o responsável para confirmar a história, a personalidade e as necessidades do animal.",
        "color": "Não informado",
        "coat": "Não informado",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Não informado",
        "ongId": "novo-lar"
    }

    , {
        "id": "coelho-nuvem",
        "name": "Nuvem",
        "species": "Coelho",
        "age": "8 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "Pessoa",
        "guardian": "Manu Silva",
        "image": "https://media.istockphoto.com/id/2246157271/pt/foto/cute-rabbit-in-a-public-park.jpg?s=612x612&w=0&k=20&c=lgXWirERgXBcHTHs-lwntYEEgjfERWALm_HANjDyEY0=",
        "description": "Coelhinha tranquila que procura uma família cuidadosa e preparada para suas necessidades.",
        "color": "Branco",
        "coat": "Médio",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Precisa de espaço seguro e alimentação adequada",
        "ongId": "patinhas"
    },
    {
        "id": "ave-pipiu",
        "name": "Pipiu",
        "species": "Ave",
        "age": "1 ano",
        "sex": "Não informado",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Marina",
        "image": "https://parrotsplace.com.br/wp-content/uploads/2020/05/Cacatua-Galerita.jpg",
        "description": "Ave dócil à procura de um lar responsável. Confirme a espécie e os cuidados necessários com o responsável.",
        "color": "Colorido",
        "coat": "Penas",
        "neutered": "Não se aplica",
        "vaccinated": "Não informado",
        "dewormed": "Não se aplica",
        "special": "Confirmar espécie e necessidades específicas",
        "ongId": null
    }

    , {
        "id": "coelho-nuvem",
        "name": "Nuvem",
        "species": "Coelho",
        "age": "8 meses",
        "sex": "Fêmea",
        "size": "Pequeno",
        "city": "São Paulo, SP",
        "source": "ONG",
        "guardian": "Patinhas Felizes",
        "image": "https://petanjo.com/blog/wp-content/uploads/2022/09/coelho-de-estimacao-2.jpg",
        "description": "Coelhinha tranquila que procura uma família cuidadosa e preparada para suas necessidades.",
        "color": "Branco",
        "coat": "Médio",
        "neutered": "Não informado",
        "vaccinated": "Não informado",
        "dewormed": "Não informado",
        "special": "Precisa de espaço seguro e alimentação adequada",
        "ongId": "patinhas"
    },
    {
        "id": "ave-pipiu",
        "name": "Pipiu",
        "species": "Ave",
        "age": "1 ano",
        "sex": "Não informado",
        "size": "Pequeno",
        "city": "Campinas, SP",
        "source": "Pessoa",
        "guardian": "Marina",
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/2007-10-28_AfricanGrayParrot_Meru.jpg/330px-2007-10-28_AfricanGrayParrot_Meru.jpg?utm_source=pt.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
        "description": "Ave dócil à procura de um lar responsável. Confirme a espécie e os cuidados necessários com o responsável.",
        "color": "Colorido",
        "coat": "Penas",
        "neutered": "Não se aplica",
        "vaccinated": "Não informado",
        "dewormed": "Não se aplica",
        "special": "Confirmar espécie e necessidades específicas",
        "ongId": null
    }
];
window.PETLAR_ONGS = [{
        "id": "patinhas",
        "name": "CÃO SEM DONO",
        "city": "São Paulo, SP",
        "count": 15,
        "image": "./assets/imagens/animais/Cao sem dono.jpg",
        "description": "Acolhimento, cuidado e novas oportunidades para animais que precisam de uma família.",
        "site": "https://www.caosemdono.com.br/",
        "email": "caosemdono@com.br",
        "phone": "11 97863-4054",
        "history": "A CÃO SEM DONO trabalha para aproximar animais resgatados de famílias responsáveis.",
        "mission": "Promover bem-estar animal e adoções conscientes."
    },
    {
        "id": "amor",
        "name": "Amor Animal",
        "city": "Rio de Janeiro, RJ",
        "count": 15,
        "image": "./assets/imagens/animais/catland.png",
        "description": "Uma rede de pessoas dedicada ao resgate e à adoção responsável.",
        "site": "https://catland.org.br/",
        "email": "catland@org.br",
        "phone": "",
        "history": "O Amor Animal reúne voluntários que apoiam o cuidado e a adoção.",
        "mission": "Construir relações duradouras entre animais e famílias."
    },
    {
        "id": "vida",
        "name": "Vida de 4 Patas",
        "city": "Belo Horizonte, MG",
        "count": 15,
        "image": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=600&q=80",
        "description": "Cuidado, respeito e carinho em cada etapa da adoção.",
        "site": "",
        "email": "contato@exemplo.org",
        "phone": "",
        "history": "A Vida de 4 Patas promove a divulgação de animais que buscam um lar.",
        "mission": "Incentivar a adoção responsável e o respeito aos animais."
    },
    {
        "id": "resgate",
        "name": "Resgate Animal",
        "city": "Curitiba, PR",
        "count": 15,
        "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=600&q=80",
        "description": "Apoio a animais resgatados e conexão com novos lares.",
        "site": "",
        "email": "contato@exemplo.org",
        "phone": "",
        "history": "O Resgate Animal é um projeto demonstrativo de proteção animal.",
        "mission": "Ampliar oportunidades de adoção com informação e cuidado."
    },
    {
        "id": "novo-lar",
        "name": "Novo Lar",
        "city": "Santos, SP",
        "count": 15,
        "image": "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=600&q=80",
        "description": "Pequenos gestos, grandes mudanças na vida dos animais.",
        "site": "",
        "email": "contato@exemplo.org",
        "phone": "",
        "history": "O Novo Lar divulga animais e orienta famílias interessadas.",
        "mission": "Ajudar cada animal a encontrar uma família preparada."
    }
];